data:
  train:
    datasets:
      - _target_: src.datasets.LJSpeechDataset
        root: "./data"
        duration: 0.5
    # limit: 32
    batch_size: 32
    num_workers: 4


generator_config:
  upsample_kernel_sizes:
    - 16
    - 16
    - 4
    - 4
  # h_u
  upsample_initial_channel: 128
  # k_r
  resblock_kernel_sizes:
    - 3
    - 7
    - 11
  # D_r
  resblock_dilation_sizes:
    - [1, 3, 5]
    - [1, 3, 5]
    - [1, 3, 5]

optimizer:
  lr: 2e-4
  betas:
    - 0.8
    - 0.98
  eps: 1e-09
  weight_decay: 1e-3

trainer_args:
  output_dir: "./output"
  max_steps: 200000
  max_grad_norm: 10.0
  warmup_steps: 1000
  logging_steps: 50
  save_steps: 10000
