data:
  train:
    datasets:
      - _target_: src.datasets.ASV_Dataset
        data_path: "./data/LA"
        split: "train"
    # limit: 32
    batch_size: 32
    num_workers: 4
  eval:
    datasets:
      - _target_: src.datasets.ASV_Dataset
        data_path: "./data/LA"
        split: "eval"
    batch_size: 64
    # limit: 64
    num_workers: 4

model:
  channels_list: [20, 20, 128, 128, 128, 128, 128]
  # channels_list: [128, 128, 512, 512, 512, 512, 512]
  agg_hidden_size: 512
  num_classes: 2
  input_abs: True

loss:
  weights: [1.0, 9.0]

optimizer:
  lr: 2e-4
  betas:
    - 0.8
    - 0.98
  eps: 1e-09
  weight_decay: 1e-4

trainer_args:
  output_dir: "./output"
  max_steps: 50000
  max_grad_norm: 2.0
  warmup_steps: 1000
  eval_steps: 5000
  logging_steps: 50
  save_steps: 5000
