data:
  train:
    datasets:
      - _target_: src.datasets.ASV_Dataset
        data_path: "./data/LA"
        split: "train"
    limit: 8
    batch_size: 8
    num_workers: 4

model:
  channels_list: [128, 128, 512, 512, 512, 512]

optimizer:
  lr: 2e-4
  betas:
    - 0.8
    - 0.98
  eps: 1e-09
  weight_decay: 1e-3

trainer_args:
  output_dir: "./output"
  max_steps: 200000
  max_grad_norm: 10.0
  warmup_steps: 10
  logging_steps: 1
  save_steps: 10000
